apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "homelab-deploy.fullname" . }}-cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    {{- include "homelab-deploy.labels" . | nindent 4 }}
spec:
  project: default

  sources:
    - repoURL: oci://quay.io/jetstack/charts/cert-manager
      path: .
      targetRevision: v1.19.1
      helm:
        valueFiles:
        - '$values/cert-manager/values-override.yaml'
    - repoURL: https://github.com/spigwitmer/homelab-stuff.git
      targetRevision: HEAD
      ref: values

  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
