apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "homelab-deploy.fullname" . }}-external-dns-pihole
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    {{- include "homelab-deploy.labels" . | nindent 4 }}
spec:
  project: default

  sources:
    - repoURL: https://github.com/spigwitmer/homelab-stuff.git
      targetRevision: HEAD
      path: pihole

  destination:
    server: "https://kubernetes.default.svc"
    namespace: pihole-system
