apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ include "homelab-deploy.fullname" . }}-prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    {{- include "homelab-deploy.labels" . | nindent 4 }}
spec:
  project: default

  sources:
    - repoURL: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
      path: .
      targetRevision: 79.8.2
      helm:
        releaseName: prometheus
        valueFiles:
        - '$values/prometheus/values-override.yaml'
    - repoURL: https://github.com/spigwitmer/homelab-stuff.git
      targetRevision: HEAD
      ref: values

  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus
